In [3]:
import numpy as np 
import pandas as pd 


In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [5]:
true_data=pd.read_csv('/Users/Basit/Downloads/archive/News _dataset/True.csv')
fake_data=pd.read_csv('/Users/Basit/Downloads/archive/News _dataset/Fake.csv')

print(true_data[0:14])
fake_data[0:10]

                                                title  \
0   As U.S. budget fight looms, Republicans flip t...   
1   U.S. military to accept transgender recruits o...   
2   Senior U.S. Republican senator: 'Let Mr. Muell...   
3   FBI Russia probe helped by Australian diplomat...   
4   Trump wants Postal Service to charge 'much mor...   
5   White House, Congress prepare for talks on spe...   
6   Trump says Russia probe will be fair, but time...   
7   Factbox: Trump on Twitter (Dec 29) - Approval ...   
8          Trump on Twitter (Dec 28) - Global Warming   
9   Alabama official to certify Senator-elect Jone...   
10  Jones certified U.S. Senate winner despite Moo...   
11  New York governor questions the constitutional...   
12  Factbox: Trump on Twitter (Dec 28) - Vanity Fa...   
13     Trump on Twitter (Dec 27) - Trump, Iraq, Syria   

                                                 text       subject  \
0   WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1 

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [6]:
print(true_data['text'][0])
true_data.columns

WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support educati

Index(['title', 'text', 'subject', 'date'], dtype='object')

In [7]:
len(true_data)


21417

In [8]:
fake_data['label'] = 1
true_data['label']=0
print(true_data.head())
fake_data.head()

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  label  
0  December 31, 2017       0  
1  December 29, 2017       0  
2  December 31, 2017       0  
3  December 30, 2017       0  
4  December 29, 2017       0  


title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  label  
0  December 31, 2017      1  
1  December 31, 2017      1  
2  December 30, 2017      1  
3  December 29, 2017      1  
4  December 25, 2017      1

In [9]:
all_data=pd.concat([fake_data, true_data])
random_permutation = np.random.permutation(len(all_data))
all_data= all_data.iloc[random_permutation]
print(all_data.columns)
all_data.head()

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')


title  \
23450  Will American Law Enforcement Lie, Cheat and F...   
15649  Lebanon PM Hariri resigns, assails Iran and He...   
14168  North Korea calls terror relisting 'serious pr...   
21360  GERMAN OFFICIAL WARNS OF CIVIL WAR BETWEEN MUS...   
9124   Trump adds new twist to immigration proposals,...   

                                                    text       subject  \
23450  21st Century Wire says The issue of honest pol...   Middle-east   
15649  BEIRUT (Reuters) - Lebanon s Prime Minister Sa...     worldnews   
14168  SEOUL (Reuters) - North Korea denounced on Wed...     worldnews   
21360  How did any EU official think their country co...     left-news   
9124   WASHINGTON (Reuters) - Republican presidential...  politicsNews   

                     date  label  
23450    February 9, 2016      1  
15649   November 4, 2017       0  
14168  November 22, 2017       0  
21360         Nov 8, 2015      1  
9124       June 15, 2016       0

In [10]:
filterd_data=all_data.loc[:, ['title', 'text', "subject", 'label']]
filterd_data.head()

title  \
23450  Will American Law Enforcement Lie, Cheat and F...   
15649  Lebanon PM Hariri resigns, assails Iran and He...   
14168  North Korea calls terror relisting 'serious pr...   
21360  GERMAN OFFICIAL WARNS OF CIVIL WAR BETWEEN MUS...   
9124   Trump adds new twist to immigration proposals,...   

                                                    text       subject  label  
23450  21st Century Wire says The issue of honest pol...   Middle-east      1  
15649  BEIRUT (Reuters) - Lebanon s Prime Minister Sa...     worldnews      0  
14168  SEOUL (Reuters) - North Korea denounced on Wed...     worldnews      0  
21360  How did any EU official think their country co...     left-news      1  
9124   WASHINGTON (Reuters) - Republican presidential...  politicsNews      0

In [24]:
filterd_data.isnull().sum()

title               0
text                0
subject             0
label               0
training_feature    0
dtype: int64

In [25]:
filterd_data['training_feature']=filterd_data['title']+' '+filterd_data['text']+' '+filterd_data['subject']
filterd_data.head()

title  \
23450  Will American Law Enforcement Lie, Cheat and F...   
15649  Lebanon PM Hariri resigns, assails Iran and He...   
14168  North Korea calls terror relisting 'serious pr...   
21360  GERMAN OFFICIAL WARNS OF CIVIL WAR BETWEEN MUS...   
9124   Trump adds new twist to immigration proposals,...   

                                                    text       subject  label  \
23450  21st Century Wire says The issue of honest pol...   Middle-east      1   
15649  BEIRUT (Reuters) - Lebanon s Prime Minister Sa...     worldnews      0   
14168  SEOUL (Reuters) - North Korea denounced on Wed...     worldnews      0   
21360  How did any EU official think their country co...     left-news      1   
9124   WASHINGTON (Reuters) - Republican presidential...  politicsNews      0   

                                        training_feature  
23450  Will American Law Enforcement Lie, Cheat and F...  
15649  Lebanon PM Hariri resigns, assails Iran and He...  
14168  North Korea calls terror relisting 'serious pr...  
21360  GERMAN OFFICIAL WARNS OF CIVIL WAR BETWEEN MUS...  
9124   Trump adds new twist to immigration proposals,...

In [26]:
X= filterd_data['training_feature'].values
y = filterd_data['label']

In [27]:
l_X=filterd_data['training_feature'].values[0:1000]
l_Y= filterd_data['label'].values[0:1000]

In [28]:
print(l_X.shape)
print(l_Y.shape)
type (l_X)

(1000,)
(1000,)


numpy.ndarray

In [29]:
print(X[0:1])

['Will American Law Enforcement Lie, Cheat and Forge Police Reports? Answer: Yes. 21st Century Wire says The issue of honest policing and institutional corruption within law enforcement has been exercised over and over, with every high-profile controversy. Certainly, 2015 had its fair share of these kind of incidents.The issue of institutional corruption still goes unattended however, as media seem to prefer the obsession of spinning every story in terms of race, or class, rather than seriously looking at the problem of devolving so much power and blind authority that are by their very nature   often corrupt.Where is the DOJ, and where is the President weighing-in? Where are the race mobs? Is this story not sexy enough for the media?This latest story should be a warning to everyone about what would likely be systemic in the fully-functioning police state which Washington DC is currently attempting to construct under the noses of its citizens  Matt Kessler GuardianSince 26-year-old Rick

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [31]:
vectorizer= TfidfVectorizer()
X=vectorizer.fit_transform(X)

In [32]:
l_vectorizer= TfidfVectorizer()
l_X=l_vectorizer.fit_transform(l_X)

In [35]:
print(type(X))
print(X.shape)
print(type(l_X))
print(l_X.shape)

<class 'scipy.sparse.csr.csr_matrix'>
(44898, 122516)
<class 'scipy.sparse.csr.csr_matrix'>
(1000, 22532)


In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, stratify=y, random_state=42)





In [37]:
l_X_train, l_X_test, l_Y_train, l_Y_test = train_test_split(l_X, l_Y, test_size = 0.2, random_state=42)

In [38]:
X_train.shape

(35918, 122516)

In [39]:
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [40]:

test_y_hat=model.predict(X_test)
print(accuracy_score(test_y_hat, Y_test))


train_y_hat = model.predict(X_train)
print(accuracy_score(train_y_hat,Y_train))

0.9922048997772829
0.9947101731722257


In [41]:
def predict(input_data):
    
    y_hat= model.predict(input_data)
    if y_hat==0:
        return "The article is Fake"
    else:
        return 'The article is not Fake'

In [42]:
print(predict(X_test[2000]))
model.predict(X_test[2000])[0]

The article is Fake


0

In [43]:
from sklearn.metrics import precision_score, recall_score, f1_score

print (precision_score(Y_train, train_y_hat,))
print (recall_score(Y_train, train_y_hat,))
print(f1_score(Y_train, train_y_hat,))


print (precision_score(Y_test, test_y_hat,))
print (recall_score(Y_test, test_y_hat,))
print(f1_score(Y_test, test_y_hat,))

0.9952591487774995
0.9946233697098749
0.9949411576761275
0.9919183326244151
0.9931856899488927
0.992551606724835


In [44]:
from sklearn.metrics import confusion_matrix
print ([['TP', 'FP'],['FN', 'TN']])
print(confusion_matrix(Y_test, test_y_hat,))
print (confusion_matrix(Y_train, train_y_hat,))

[['TP', 'FP'], ['FN', 'TN']]
[[4246   38]
 [  32 4664]]
[[17044    89]
 [  101 18684]]


In [45]:
from sklearn import svm

#Create a svm Classifier
model = svm.SVC(kernel='linear') # Linear Kernel
clf_poly=clf = svm.SVC(kernel='poly') # Polynomial kernel

In [46]:
print(X_train.shape)
# X_train.iloc[0:1000].shape

(35918, 122516)


In [47]:
#Train the model using the training sets
model.fit(l_X_train, l_Y_train)
#clf_poly.fit(X_train,Y_train)

SVC(kernel='linear')

In [48]:
y_pred = model.predict(l_X_test)



In [49]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))

0.98
0.9814814814814815
0.9814814814814815
0.9814814814814815
[[ 90   2]
 [  2 106]]


In [50]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(l_X_train, l_Y_train)

RandomForestClassifier()

In [51]:
y_pred = model.predict(l_X_test)

In [52]:
print (y_pred)


[1 1 1 1 1 0 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0
 1 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1
 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0
 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 1 1
 0 0 1 0 1 0 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 1
 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0]


In [53]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,confusion_matrix


print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))

0.995
0.9908256880733946
1.0
0.9953917050691244
[[ 91   1]
 [  0 108]]


In [54]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [55]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0], dtype=int64)

In [56]:
model.fit(l_X_train.toarray(), l_Y_train)

GaussianNB()

In [57]:
print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.995
0.9908256880733946
1.0
0.9953917050691244
[[ 91   1]
 [  0 108]]
